name: CI

# Contains all the things to do after code is merged into master
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Test:
    name: RunCI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci 

      - name: Run tests
        run: npm test

      - name: Run Eslint
        run: npm run lint